// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzncigpifeqxvjkajcft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6bmNpZ3BpZmVxeHZqa2FqY2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NDQ0MTEsImV4cCI6MjA5MzIyMDQxMX0.o0Q2w-S4jgmavFiaxYiKWl7cc-jv73WWn4HtXwKzwyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});