// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpevbhshkopniyxzlqta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZXZiaHNoa29wbml5eHpscXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NDgwNDIsImV4cCI6MjA5MzIyNDA0Mn0.ywfcYv-fYs7otPbXofBc4bSkzmoJXZK5tzRrkbTT7Is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});